In [1]:
#importation du package
import h2o

In [2]:
#démarrage H2O
h2o.init()

Checking whether there is an H2O instance running at http://localhost:54321 ..... not found.
Attempting to start a local H2O server...
; Java HotSpot(TM) Client VM (build 25.45-b02, mixed mode, sharing)


C:\ProgramData\Anaconda3\lib\site-packages\h2o\backend\server.py:385: UserWarning:   You have a 32-bit version of Java. H2O works best with 64-bit Java.
  Please download the latest 64-bit Java SE JDK from Oracle.

  warn("  You have a 32-bit version of Java. H2O works best with 64-bit Java.\n"


  Starting server from C:\ProgramData\Anaconda3\lib\site-packages\h2o\backend\bin\h2o.jar
  Ice root: C:\Users\ADMINI~1\AppData\Local\Temp\tmps6p5qzdx
  JVM stdout: C:\Users\ADMINI~1\AppData\Local\Temp\tmps6p5qzdx\h2o_Administrateur_started_from_python.out
  JVM stderr: C:\Users\ADMINI~1\AppData\Local\Temp\tmps6p5qzdx\h2o_Administrateur_started_from_python.err
  Server is running at http://127.0.0.1:54321
Connecting to H2O server at http://127.0.0.1:54321 ... successful.


--------------------------  ---------------------------------------------------------
H2O_cluster_uptime:         04 secs
H2O_cluster_timezone:       Europe/Paris
H2O_data_parsing_timezone:  UTC
H2O_cluster_version:        3.32.0.2
H2O_cluster_version_age:    2 months and 18 days
H2O_cluster_name:           H2O_from_python_Administrateur_vo6v8z
H2O_cluster_total_nodes:    1
H2O_cluster_free_memory:    247.5 Mb
H2O_cluster_total_cores:    0
H2O_cluster_allowed_cores:  0
H2O_cluster_status:         accepting new members, healthy
H2O_connection_url:         http://127.0.0.1:54321
H2O_connection_proxy:       {"http": null, "https": null}
H2O_internal_security:      False
H2O_API_Extensions:         Amazon S3, Algos, AutoML, Core V3, TargetEncoder, Core V4
Python_version:             3.7.4 final
--------------------------  ---------------------------------------------------------

# Prétraitement des données

In [3]:
#changer le répertoire courant
import os
os.chdir("C:/Users/Administrateur/Documents/H20 ipynb")

In [4]:
#chargement des données
cardio = h2o.import_file("cardio.csv")

Parse progress: |█████████████████████████████████████████████████████████| 100%


In [5]:
#affichage des premières valeurs
print(cardio.head(10))

id age gender height weight ap_hi ap_lo cholesterol gluc smoke alco active cardio 
 
 
 0 18393 2 168 62 110 80 1 1 0 0 1 0 
 1 20228 1 156 85 140 90 3 1 0 0 1 1 
 2 18857 1 165 64 130 70 3 1 0 0 0 1 
 3 17623 2 169 82 150 100 1 1 0 0 1 1 
 4 17474 1 156 56 100 60 1 1 0 0 0 0 
 8 21914 1 151 67 120 80 2 2 0 0 0 0 
 9 22113 1 157 93 130 80 3 1 0 0 1 0 
 12 22584 2 178 95 130 90 3 3 0 0 1 1 
 13 17668 1 158 71 110 70 1 1 0 0 1 0 
 14 19834 1 164 68 110 60 1 1 0 0 0 0

In [6]:
#affichage du type
print(type(cardio))

<class 'h2o.frame.H2OFrame'>


In [7]:
#dimension
print(cardio.shape)

(70000, 13)


In [8]:
#affichage de la liste des colonnes
print(cardio.col_names)

['id', 'age', 'gender', 'height', 'weight', 'ap_hi', 'ap_lo', 'cholesterol', 'gluc', 'smoke', 'alco', 'active', 'cardio']


In [9]:
# Resume de donnée
cardio.describe()

Rows:70000
Cols:13




id age gender height weight ap_hi ap_lo cholesterol gluc smoke alco active cardio 
 
 
 type int int int int real int int int int int int int int 
 mins 0.0 10798.0 1.0 55.0 10.0 -150.0 -70.0 1.0 1.0 0.0 0.0 0.0 0.0 
 mean 49972.41989999998 19468.86581428571 1.3495714285714273 164.35922857142862 74.20568999999999 128.81728571428567 96.63041428571428 1.3668714285714283 1.2264571428571436 0.08812857142857143 0.053771428571428574 0.8037285714285715 0.4997 
 maxs 99999.0 23713.0 2.0 250.0 200.0 16020.0 11000.0 3.0 3.0 1.0 1.0 1.0 1.0 
 sigma 28851.30232317291 2467.2516672414017 0.4768380155828637 8.210126364538034 14.395756678511377 154.01141945609132 188.4725302963903 0.6802503486993811 0.5722702766138451 0.2834838167699352 0.22556770360410489 0.3971790635049283 0.5000034814661862 
 zeros 1 0 0 0 0 0 21 0 0 63831 66236 13739 35021 
 missing 0 0 0 0 0 0 0 0 0 0 0 0 0 
 0 0.0 18393.0 2.0 168.0 62.0 110.0 80.0 1.0 1.0 0.0 0.0 1.0 0.0 
 1 1.0 20228.0 1.0 156.0 85.0 140.0 90.0 3.0 1.0 0.0 0.0 1.0 1.0 
 2 2.0 18857.0 1.0 165.0 64.0 130.0 70.0 3.0 1.0 0.0 0.0 0.0 1.0 
 3 3.0 17623.0 2.0 169.0 82.0 150.0 100.0 1.0 1.0 0.0 0.0 1.0 1.0 
 4 4.0 17474.0 1.0 156.0 56.0 100.0 60.0 1.0 1.0 0.0 0.0 0.0 0.0 
 5 8.0 21914.0 1.0 151.0 67.0 120.0 80.0 2.0 2.0 0.0 0.0 0.0 0.0 
 6 9.0 22113.0 1.0 157.0 93.0 130.0 80.0 3.0 1.0 0.0 0.0 1.0 0.0 
 7 12.0 22584.0 2.0 178.0 95.0 130.0 90.0 3.0 3.0 0.0 0.0 1.0 1.0 
 8 13.0 17668.0 1.0 158.0 71.0 110.0 70.0 1.0 1.0 0.0 0.0 1.0 0.0 
 9 14.0 19834.0 1.0 164.0 68.0 110.0 60.0 1.0 1.0 0.0 0.0 0.0 0.0

In [10]:
# vérifier les types de données analysés par H2O
cardio.types

{'id': 'int',
 'age': 'int',
 'gender': 'int',
 'height': 'int',
 'weight': 'real',
 'ap_hi': 'int',
 'ap_lo': 'int',
 'cholesterol': 'int',
 'gluc': 'int',
 'smoke': 'int',
 'alco': 'int',
 'active': 'int',
 'cardio': 'int'}

In [11]:
cardio["cardio"] = cardio["cardio"].asfactor()

In [12]:
#cardio est bien un type facteur
cardio['cardio'].isfactor() 

[True]

In [13]:
#nombre de niveaux (modalités) de "diabete"
cardio['cardio'].levels()

[['0', '1']]

# Subdivision en échantillons d’apprentissage et de test

In [14]:
#subdivision
cardioTrain,cardioTest = cardio.split_frame(ratios=[0.8],seed=1)

In [15]:
#vérification train
cardioTrain.shape

(56007, 13)

In [16]:
#vérification test
cardioTest.shape

(13993, 13)

# IMPLEMENTATION DES ALGORITHMES 

# ALGORITHME DE LSC

In [25]:
import numpy as np
import matplotlib.pyplot as plt
from sklearn.cluster import KMeans
from sklearn.datasets import make_blobs
from sklearn.metrics.pairwise import pairwise_distances
import scipy


def find_p(X, start=1, end=10):
    
    min_size=[]
    number_of_clusters=[]
    for i in range(start,end+1):
        min_size.append(i)   
        number_of_clusters.append(KMeans(n_clusters=i).fit(X).inertia_)
    _, ax=plt.subplots()
    
    ax.set(ylabel='Inertia', xlabel='Number of clusters', title='The elbow method')
    plt.xticks(np.arange(start,end, 1))    
    plt.plot(min_size,number_of_clusters)
    plt.show()    

def get_Landmarks(X, p, method="random"):
    if method=="random":
        N = len(X)
        perm= np.random.permutation(np.arange(N))
        print(perm)
        landmarks = X[perm[:p],:]
        return landmarks
    else:
        kmeans_model=KMeans(n_clusters=p).fit(X)
        return kmeans_model.cluster_centers_


def gaussian_kernel(dist_mat, bandwidth):
    return np.exp(-dist_mat / (2*bandwidth**2))

def compose_Sparse_ZHat_Matrix(X, landmarks, bandwidth, r):
    dist_mat=pairwise_distances(X,landmarks)
    sim_mat=gaussian_kernel(dist_mat, bandwidth)
    
    Zhat = np.zeros(sim_mat.shape)

    for i in range(Zhat.shape[0]):
        #may need j.sort.selectperm
        top_Landmarks_indices = np.argsort(-sim_mat[i,:])[:r]
        top_Landmarks_coefs = sim_mat[i,top_Landmarks_indices]
        top_Landmarks_coefs /= np.sum(top_Landmarks_coefs)
        Zhat[i, top_Landmarks_indices] = top_Landmarks_coefs
    #May be wrong    
    diagm=np.sum(Zhat, axis=0)**(-1/2)
    return diagm*Zhat

def LSC_Clustering(X, n_clusters, n_landmarks, method, non_zero_landmark_weights, bandwidth):
    landmarks = get_Landmarks(X, n_landmarks, method)
    Zhat = compose_Sparse_ZHat_Matrix(X, landmarks, bandwidth, non_zero_landmark_weights)
    svd_result = np.linalg.svd(Zhat, full_matrices=False)[0]
    clustering_result = KMeans(n_clusters=n_clusters).fit(svd_result)
    return clustering_result
#Test get_Landmarks
test1=False
if test1:
    X,y= cardioTrain.as_np(),cardioTest.as_np()

    landmarks_rand=get_Landmarks(X,2)
    print(landmarks_rand)

    landmarks_kmeans=get_Landmarks(X,2,"KMeans")
    print(landmarks_kmeans)
    find_p(X)
    print(compose_Sparse_ZHat_Matrix(X, landmarks_kmeans, 1, 5))

test2=True
if test2:
    X,y=cardioTrain.as_np(),cardioTest.as_np()
    labels=LSC_Clustering(X, 2, 4, "Kmeans", 4, 0.5).labels_
    
    plt.scatter(X[:,0],X[:,1], c=labels)
    plt.show()

AttributeError: 'H2OFrame' object has no attribute 'as_np'

In [32]:
# Importation des bibliothèques principales
import pandas as pd
import numpy as np
import seaborn as sns
import matplotlib.pyplot as plt

In [34]:
# Lecture des données
cardio = pd.read_csv('cardio.csv',sep=";",header=0,index_col=0)

In [35]:
cardio

age  gender  height  weight  ap_hi  ap_lo  cholesterol  gluc  smoke  \
id                                                                             
0      18393       2     168    62.0    110     80            1     1      0   
1      20228       1     156    85.0    140     90            3     1      0   
2      18857       1     165    64.0    130     70            3     1      0   
3      17623       2     169    82.0    150    100            1     1      0   
4      17474       1     156    56.0    100     60            1     1      0   
...      ...     ...     ...     ...    ...    ...          ...   ...    ...   
99993  19240       2     168    76.0    120     80            1     1      1   
99995  22601       1     158   126.0    140     90            2     2      0   
99996  19066       2     183   105.0    180     90            3     1      0   
99998  22431       1     163    72.0    135     80            1     2      0   
99999  20540       1     170    72.0    120     80            2     1      0   

       alco  active  cardio  
id                           
0         0       1       0  
1         0       1       1  
2         0       0       1  
3         0       1       1  
4         0       0       0  
...     ...     ...     ...  
99993     0       1       0  
99995     0       1       1  
99996     1       0       1  
99998     0       0       1  
99999     0       1       0  

[70000 rows x 12 columns]

In [36]:
#transformation en matrice numpy - seul reconnu par scikit-learn
cardio = cardio.values

# Subdivision en échantillons d’apprentissage et de test

In [38]:
print(cardio[:,0:12])

[[1.8393e+04 2.0000e+00 1.6800e+02 ... 0.0000e+00 1.0000e+00 0.0000e+00]
 [2.0228e+04 1.0000e+00 1.5600e+02 ... 0.0000e+00 1.0000e+00 1.0000e+00]
 [1.8857e+04 1.0000e+00 1.6500e+02 ... 0.0000e+00 0.0000e+00 1.0000e+00]
 ...
 [1.9066e+04 2.0000e+00 1.8300e+02 ... 1.0000e+00 0.0000e+00 1.0000e+00]
 [2.2431e+04 1.0000e+00 1.6300e+02 ... 0.0000e+00 0.0000e+00 1.0000e+00]
 [2.0540e+04 1.0000e+00 1.7000e+02 ... 0.0000e+00 1.0000e+00 0.0000e+00]]


In [39]:
#X matrice des var. explicatives
X = cardio[:,0:11]

In [40]:
print(cardio[:,11])

[0. 1. 1. ... 1. 1. 0.]


In [41]:
#y vecteur de la var. à prédire
y = cardio[:,11]

# ALGORITHME DE LSC

In [52]:
import numpy as np
import matplotlib.pyplot as plt
from sklearn.cluster import KMeans
from sklearn.datasets import make_blobs
from sklearn.metrics.pairwise import pairwise_distances
import scipy


def find_p(X, start=1, end=10):
    
    min_size=[]
    number_of_clusters=[]
    for i in range(start,end+1):
        min_size.append(i)   
        number_of_clusters.append(KMeans(n_clusters=i).fit(X).inertia_)
    _, ax=plt.subplots()
    
    ax.set(ylabel='Inertia', xlabel='Number of clusters', title='The elbow method')
    plt.xticks(np.arange(start,end, 1))    
    plt.plot(min_size,number_of_clusters)
    plt.show()    

def get_Landmarks(X, p, method="random"):
    if method=="random":
        N = len(X)
        perm= np.random.permutation(np.arange(N))
        print(perm)
        landmarks = X[perm[:p],:]
        return landmarks
    else:
        kmeans_model=KMeans(n_clusters=p).fit(X)
        return kmeans_model.cluster_centers_


def gaussian_kernel(dist_mat, bandwidth):
    return np.exp(-dist_mat / (2*bandwidth**2))

def compose_Sparse_ZHat_Matrix(X, landmarks, bandwidth, r):
    dist_mat=pairwise_distances(X,landmarks)
    sim_mat=gaussian_kernel(dist_mat, bandwidth)
    
    Zhat = np.zeros(sim_mat.shape)

    for i in range(Zhat.shape[0]):
        #may need j.sort.selectperm
        top_Landmarks_indices = np.argsort(-sim_mat[i,:])[:r]
        top_Landmarks_coefs = sim_mat[i,top_Landmarks_indices]
        top_Landmarks_coefs /= np.sum(top_Landmarks_coefs)
        Zhat[i, top_Landmarks_indices] = top_Landmarks_coefs
    #May be wrong    
    diagm=np.sum(Zhat, axis=0)**(-1/2)
    return diagm*Zhat

def LSC_Clustering(X, n_clusters, n_landmarks, method, non_zero_landmark_weights, bandwidth):
    landmarks = get_Landmarks(X, n_landmarks, method)
    Zhat = compose_Sparse_ZHat_Matrix(X, landmarks, bandwidth, non_zero_landmark_weights)
    svd_result = np.linalg.svd(Zhat, full_matrices=False)[0]
    clustering_result = KMeans(n_clusters=n_clusters).fit(svd_result)
    return clustering_result
#Test get_Landmarks
test1=False
if test1:
    X,y= X,y

    landmarks_rand=get_Landmarks(X,2)
    print(landmarks_rand)

    landmarks_kmeans=get_Landmarks(X,2,"KMeans")
    print(landmarks_kmeans)
    find_p(X)
    print(compose_Sparse_ZHat_Matrix(X, landmarks_kmeans, 1, 5))

test2=True
if test2:
    X,y=X,y
    labels=LSC_Clustering(X,2, 4, "Kmeans", 4, 0.5).labels_
    
    plt.scatter(X[:,0],X[:,1], c=labels)
    plt.show()

C:\ProgramData\Anaconda3\lib\site-packages\ipykernel_launcher.py:48: RuntimeWarning: invalid value encountered in true_divide


LinAlgError: SVD did not converge

In [53]:
np.__version__

'1.19.5'